name: git-profile
version: 1.1.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: git_profile_command
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
url: https://github.com/NiklasRosenstein/git-profile
description: Easily switch between Git configurations on a per-repository basis.
requirements:
- python ^3.6
- databind.core ^0.7.0
- databind.json ^0.6.1
- nr.fs ^1.6.2
dev-requirements:
- databind.mypy ^0.0.1
entrypoints:
  console_scripts:
  - git-profile = git_profile_command:main
